[build]
  command = "npm install"       # No build step needed for your setup
  publish = "public"           # Your static files directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200                 # SPA fallback for all routes

[functions]
  directory = "netlify/functions"  # Correct functions location
  node_bundler = "esbuild"     # Recommended for faster builds